const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.progressbar,
		C3.Behaviors.Rotate,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Спрайт: 0},
	{Индикатор: 0},
	{Поворот: 0},
	{Платформер: 0},
	{МячЛевый: 0},
	{ТайловыйФон: 0},
	{Влево: 0},
	{Вправо: 0},
	{Мышь: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{МячПравый: 0},
	{Счет: 0},
	{Жизни: 0},
	{ЛинияПола: 0},
	{ОстЖиз: 0},
	{ОстЖиз2: 0},
	{ОстЖиз3: 0},
	{ОтличноПоиграли: 0},
	{ИтоговыйСчет2: 0},
	{Спрайт5: 0},
	{ЕщеРаз: 0},
	{да: 0},
	{СтартовыйТекст: 0},
	{КнопкаНачать: 0},
	{Начать: 0},
	{Кнопка: 0},
	{ТомСидит: 0},
	{Тач: 0},
	{ОстЖиз4: 0},
	{ОстЖиз5: 0},
	{Спрайт2: 0},
	{ПропускМячей: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Индикатор: class extends self.IProgressBarInstance {},
	МячЛевый: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Влево: class extends self.ISpriteInstance {},
	Вправо: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	МячПравый: class extends self.ISpriteInstance {},
	Счет: class extends self.ITextInstance {},
	Жизни: class extends self.ITextInstance {},
	ЛинияПола: class extends self.ISpriteInstance {},
	ОстЖиз: class extends self.ISpriteInstance {},
	ОстЖиз2: class extends self.ISpriteInstance {},
	ОстЖиз3: class extends self.ISpriteInstance {},
	ОтличноПоиграли: class extends self.ITextInstance {},
	ИтоговыйСчет2: class extends self.ITextInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	ЕщеРаз: class extends self.ITextInstance {},
	да: class extends self.ITextInstance {},
	СтартовыйТекст: class extends self.ITextInstance {},
	КнопкаНачать: class extends self.ISpriteInstance {},
	Начать: class extends self.ITextInstance {},
	Кнопка: class extends self.IButtonInstance {},
	ТомСидит: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	ОстЖиз4: class extends self.ISpriteInstance {},
	ОстЖиз5: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {}
}